import './Cart.css';

function Cart() {
    
    return(
    <div>CartCartCartCartCartCartCartCartCartCartCartCartCartCartCartCartCartCartCartCartCartCartCartCartCartCartCartCartCartCartCartCartCartCartCartCartCartCartCartCartCartCartCartCartCartCartCartCartCartCartCartCartCartCartCartCartCartCartCartCartCartCartCartCartCartCartCartCartCartCartCartCartCartCartCartCartCartCartCartCartCartCartCartCartCartCartCartCartCartCartCartCartCartCartCartCartCartCartCartCartCartCartCartCartCartCartCartCartCartCartCartCartCartCartCartCartCartCartCartCartCartCartCartCartCartCartCartCart
    </div>
    )
}

export default Cart;